### PR TITLE
feat: implement emoji autocompletion

### PR DESCRIPTION
**Pull request by Sharp-Eyes**
## Description

This PR introduces an emoji previewer/autocompleter that is activated when at least the first three characters of any emoji are entered into the chat bar, including the leading colon. For example:

image

This window can be navigated using the up/down arrow keys, and a selection can be made with tab/enter or a mouse click.

If the emoji is autocompleted mid-sentence, a space is automatically added if the character after the emoji is *not* already whitespace, otherwise the existing whitespace is maintained as-is.

## This is a **Logic Change**
- [x] Changes have been tested.

## This is a **UI Change**
- [x] This has been previewed and looks as intended

### CODE REVIEW

**Comment by EnokiUN** [comment]
is this good and finish

**Comment by Sharp-Eyes** [comment]
I think is good and finish yes

cool

**Comment by Sharp-Eyes** [comment]
it isn't

**Comment by EnokiUN** [comment]
so that was a lie

**Comment by Sharp-Eyes** [comment]
it is

**Pull request merged**
